### PR TITLE
Expose readable path from TrieRouter

### PR DESCRIPTION
**Pull request by MrLotU**
For http://github.com/vapor-community/VaporMonitoring we would like to be able to get a hold of the `[PathComponent].readable` to group our metrics by. This PR aims to expose this from `TrieRouter` so we can pick it up in vapor/vapor

### Checklist

- [x] Circle CI is passing (code compiles and passes tests).
- [x] There are no breaking changes to public API.
- [x] New test cases have been added where appropriate.
- [x] All new code has been commented with doc blocks `///`.

### CODE REVIEW

**Comment by twof** [comment]
@MrLotU can you check out those failing linux tests?

**Comment by twof** [comment]
Ahh we don't have perf tests on v3.

@MrLotU are you planning on doing the same thing for v4?

**Comment by MrLotU** [comment]
@twof I can’t reproduce the failing linux test locally 😅😱. As for Vapor 4, I might, depending on how we decide to implement swift-metrics in Vapor 4. I’ll discuss with Tanner to see what route we should take.

**Comment by MrLotU** [comment]
I fixed the failing tests. Would love some input on the function name 😄

**Comment by MrLotU** [comment]
On Vapor 4 it could, but not on Vapor 3 sadly.

**Pull request closed without merging**
