### PR TITLE
Downstream Introduced

### PR DESCRIPTION
**Pull request by twof**

### CODE REVIEW

**Comment by 0xTim** [comment]
This is cool!

**Review by 0xTim — APPROVED** [review]
I think this is a great thing to try - will let the other core team member chime in

**Comment by gwynne** [comment]
> I think this is a great thing to try - will let the other core team member chime in
Darn it, Tim, now we have to try to figure out whether it's me or @siemensikkema you're implicitly refusing to acknowledge with your so-totally-not-a-typo singular noun... 🤣

Joking aside, I agree - let's see how it goes. I'm just holding my "Approve" review until I have a chance to suggest some minor improvements to the GH Action workflow, which I'll do shortly.

**Comment by gwynne** [comment]
@vzsg Remind me what this was supposed to actually do? 😅

**Comment by twof** [comment]
@gwynne the goal of downstream was to loosely bind source files to documentation, so developers can be alerted that documentation changes may be required to go along with their code changes.

**Comment by gwynne** [comment]
@twof As it turned out, I eventually thought to actually look at your code- after having already asked, of course 😆 With the new DocC support @0xTim's been adding, this is probably not a direction we'll end up going.

And even aside that, this PR was pretty ancient, not to mention the last one open on `routing-kit`, so I took the opportunity to get at least one of Vapor's repos down to zero open PRs 😅

**Pull request closed without merging**
